"""Webhook Security Module.

Provides webhook signature verification for secure webhook processing.
Uses HMAC-SHA256 for signature validation to ensure webhooks come from
authorized sources.
"""

import hashlib
import hmac

from ...core.config import settings
from ...core.logging import get_logger

logger = get_logger(__name__)


def verify_webhook_signature(payload: str, signature: str) -> bool:
    """Verify webhook signature for security using HMAC-SHA256.

    This ensures webhooks are coming from authorized sources by validating
    that the signature in the X-Webhook-Signature header matches the
    expected signature computed from the payload using a shared secret.

    Security Features:
    - Uses HMAC-SHA256 for cryptographic signature
    - Uses constant-time comparison to prevent timing attacks
    - Requires shared secret (WEBHOOK_SECRET) configured in settings

    Args:
        payload: Request payload as JSON string (must match exactly what was signed)
        signature: HMAC signature from X-Webhook-Signature header

    Returns:
        True if signature is valid, False otherwise

    Example:
        ```python
        payload = '{"application_id": "123", "status": "approved"}'
        signature = "abc123..."  # From X-Webhook-Signature header

        if verify_webhook_signature(payload, signature):
            # Process webhook
        else:
            # Reject webhook
        ```
    """
    if not signature:
        logger.warning("Empty signature provided for webhook verification")
        return False

    if not payload:
        logger.warning("Empty payload provided for webhook verification")
        return False

    expected_signature = hmac.new(
        settings.WEBHOOK_SECRET.encode('utf-8'),
        payload.encode('utf-8'),
        hashlib.sha256
    ).hexdigest()

    is_valid = hmac.compare_digest(signature, expected_signature)

    if not is_valid:
        logger.warning(
            "Webhook signature verification failed",
            extra={
                'signature_length': len(signature),
                'expected_length': len(expected_signature)
            }
        )

    return is_valid


def generate_webhook_signature(payload: str) -> str:
    """Generate webhook signature for testing purposes.

    This function generates a valid signature for a given payload,
    which is useful for testing webhook endpoints.

    Note: This should only be used in development/testing.
    In production, the signature should be generated by the webhook sender.

    Args:
        payload: Request payload as JSON string

    Returns:
        HMAC-SHA256 signature as hex string

    Example:
        ```python
        payload = '{"application_id": "123", "status": "approved"}'
        signature = generate_webhook_signature(payload)
        # Use signature in X-Webhook-Signature header
        ```
    """
    return hmac.new(
        settings.WEBHOOK_SECRET.encode('utf-8'),
        payload.encode('utf-8'),
        hashlib.sha256
    ).hexdigest()

