"""Monitoring Infrastructure - Metrics and Tracing."""

from .metrics import (
    CONTENT_TYPE_LATEST,
    applications_by_country,
    applications_by_status,
    applications_created_total,
    applications_processed_total,
    cache_connection_status,
    cache_errors_total,
    cache_hits_total,
    cache_misses_total,
    cache_operations_total,
    db_connections_active,
    db_query_duration_seconds,
    generate_latest,
    http_request_duration_seconds,
    http_requests_in_progress,
    http_requests_total,
    provider_circuit_breaker_state,
    provider_request_duration_seconds,
    provider_requests_total,
    worker_task_duration_seconds,
    worker_tasks_in_progress,
    worker_tasks_total,
)
from .tracing import (
    extract_trace_context,
    get_current_span,
    get_tracer,
    inject_trace_context,
    set_current_span,
    setup_tracing,
)

__all__ = [
    # Metrics
    "applications_created_total",
    "applications_processed_total",
    "applications_by_status",
    "applications_by_country",
    "provider_requests_total",
    "provider_request_duration_seconds",
    "provider_circuit_breaker_state",
    "cache_hits_total",
    "cache_misses_total",
    "cache_connection_status",
    "cache_errors_total",
    "cache_operations_total",
    "db_connections_active",
    "db_query_duration_seconds",
    "http_requests_total",
    "http_request_duration_seconds",
    "http_requests_in_progress",
    "worker_tasks_total",
    "worker_task_duration_seconds",
    "worker_tasks_in_progress",
    "generate_latest",
    "CONTENT_TYPE_LATEST",
    # Tracing
    "setup_tracing",
    "get_tracer",
    "get_current_span",
    "set_current_span",
    "extract_trace_context",
    "inject_trace_context",
]
