from ..strategies.base import BankingData
from .base import BankingProvider
from .mock import MockDataGeneratorFactory


class MockBankingProvider(BankingProvider):
    """Mock implementation of BankingProvider for development/testing."""

    def __init__(self, country_code: str):
        """Initialize the mock provider for a specific country.

        Args:
            country_code: ISO 3166-1 alpha-2 country code (e.g., "BR", "ES")
        """
        # Create country-specific generator using factory
        self.generator = MockDataGeneratorFactory.create(country_code)
        
        # Initialize base provider with generator's provider name
        super().__init__(
            provider_name=self.generator.provider_name,
            country_code=country_code
        )

    async def fetch_banking_data(
        self,
        document: str,
        full_name: str
    ) -> BankingData:
        """Fetch mock banking data using country-specific strategy.

        The mock data is generated by the country-specific generator,
        ensuring consistent results for testing.

        Args:
            document: Identity document number
            full_name: Full name of the applicant

        Returns:
            BankingData with mock information
        """
        return await self.generator.generate(document, full_name)
